# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# # Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Site settings
title: whybhav
email: me@whybhav.in
description: >- 
  Personal portfolio and blog of Vaibhav (bhav) - a 24 y/o graduate student who loves making cool stuff, photography, and writing about technology and life.
baseurl: "" # Leave empty for username.github.io sites
url: "https://whybhav.in"
github_username: codebhav

# SEO and social
author: Vaibhav Achuthananda
tagline: "Personal portfolio and blog"

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-seo-tag

# Collections
collections:
    photos:
        output: true
        permalink: /photos/:path/

# Defaults
defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          comments: true
          author: Vaibhav Achuthananda
    - scope:
          path: ""
          type: "photos"
      values:
          layout: "photo"
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "page"
          author: Vaibhav Achuthananda

# SEO defaults
defaults:
  - scope:
      path: ""
    values:
      image: /social-preview.png

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    blanklines: false
    profile: false

# Exclude from processing
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor/
    - .gitignore
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile.lock
    - node_modules/